apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logging-ext
  namespace: kube-system
  labels: 
    app: logging-ext
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logging-ext
  template:
    metadata:
      labels:
        app: logging-ext
      annotations:
        prometheus.io/scrape2: "true"
    spec:
      containers:
      - name: logging-ext
        image: a8uhnf/logging-ext:1.0
        imagePullPolicy: Always
        ports:
        - name: hello
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: "logging-ext-svc"
  namespace: kube-system
  annotations:
    prometheus.io/scrape2: "true"
spec:
  selector:
    app: "logging-ext"
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer


