kind: Service
apiVersion: v1
metadata:
  name: "frontend"
  namespace: kube-system
spec:
  selector:
    app: "frontend"
  ports:
    - protocol: "TCP"
      port: 443
      targetPort: 443
  type: LoadBalancer