apiVersion: v1
kind: Service
metadata:
  name: hanifa-test
  labels:
    app: hanifa-test-svc
spec:
  type: LoadBalancer
  selector:
    app: "hanifa-test"
  ports:
  - protocol: "TCP"
    port: 7778
    targetPort: 7778