// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	HelloReq
	HelloResp
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloReq struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloReq) Reset()                    { *m = HelloReq{} }
func (m *HelloReq) String() string            { return proto.CompactTextString(m) }
func (*HelloReq) ProtoMessage()               {}
func (*HelloReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResp struct {
	Count int32 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *HelloResp) Reset()                    { *m = HelloResp{} }
func (m *HelloResp) String() string            { return proto.CompactTextString(m) }
func (*HelloResp) ProtoMessage()               {}
func (*HelloResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloResp) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*HelloReq)(nil), "api.HelloReq")
	proto.RegisterType((*HelloResp)(nil), "api.HelloResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for HelloHanifa service

type HelloHanifaClient interface {
	HelloHanifa(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error)
}

type helloHanifaClient struct {
	cc *grpc.ClientConn
}

func NewHelloHanifaClient(cc *grpc.ClientConn) HelloHanifaClient {
	return &helloHanifaClient{cc}
}

func (c *helloHanifaClient) HelloHanifa(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloResp, error) {
	out := new(HelloResp)
	err := grpc.Invoke(ctx, "/api.HelloHanifa/HelloHanifa", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HelloHanifa service

type HelloHanifaServer interface {
	HelloHanifa(context.Context, *HelloReq) (*HelloResp, error)
}

func RegisterHelloHanifaServer(s *grpc.Server, srv HelloHanifaServer) {
	s.RegisterService(&_HelloHanifa_serviceDesc, srv)
}

func _HelloHanifa_HelloHanifa_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloHanifaServer).HelloHanifa(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HelloHanifa/HelloHanifa",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloHanifaServer).HelloHanifa(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloHanifa_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.HelloHanifa",
	HandlerType: (*HelloHanifaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HelloHanifa",
			Handler:    _HelloHanifa_HelloHanifa_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 127 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x92, 0xe3, 0xe2, 0xf0, 0x48,
	0xcd, 0xc9, 0xc9, 0x0f, 0x4a, 0x2d, 0x14, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x14, 0xb9, 0x38, 0xa1, 0xf2, 0xc5, 0x05, 0x42,
	0x22, 0x5c, 0xac, 0xc9, 0xf9, 0xa5, 0x79, 0x25, 0x60, 0x15, 0xac, 0x41, 0x10, 0x8e, 0x91, 0x2d,
	0x17, 0x37, 0x58, 0x89, 0x47, 0x62, 0x5e, 0x66, 0x5a, 0xa2, 0x90, 0x1e, 0x2a, 0x97, 0x57, 0x0f,
	0x64, 0x23, 0xcc, 0x0e, 0x29, 0x3e, 0x64, 0x6e, 0x71, 0x81, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x35,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xed, 0x73, 0x35, 0x47, 0x9a, 0x00, 0x00, 0x00,
}
