apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: httpd
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: httpd
      beatbox: "true"
  serviceName: dormammu
  template:
    metadata:
      annotations:
        date: "1234567890"
      creationTimestamp: null
      labels:
        app: httpd
        beatbox: "true"
    spec:
      containers:
      - image: docker.io/a8uhnf/httpd:v1.0.0
        imagePullPolicy: Always
        name: httpd
        resources: {}
        securityContext:
          procMount: Default
          runAsUser: 0
        
        
      restartPolicy: Always
      securityContext: {}