apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-go2
  labels: 
    app: hello-go2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-go2
  template:
    metadata:
      labels:
        app: hello-go2
      annotations:
        prometheus.io/scrape2: "true"
    spec:
      containers:
      - name: hello-go2
        image: a8uhnf/go:3.0
        imagePullPolicy: Always
        ports:
        - name: hello
          containerPort: 8087
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /hello
            port: 8087
          initialDelaySeconds: 30
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 3
---
kind: Service
apiVersion: v1
metadata:
  name: "go-svc2"
  annotations:
    prometheus.io/scrape2: "true"
    cloud.google.com/load-balancer-type: "Internal"
spec:
  selector:
    app: "hello-go2"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8087
  type: ClusterIP


