apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-go
  namespace: kube-system
  labels: 
    app: hello-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: hello-go
        image: a8uhnf/go:1.0
        imagePullPolicy: Always
        ports:
        - name: hello
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: "go-svc"
  namespace: kube-system
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: "hello-go"
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer


